//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportFormASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportationRequest
    {
        public System.Guid idTransportationRequest { get; set; }
        public System.Guid idTranshipmentMethod { get; set; }
        public Nullable<System.Guid> idDateMonth { get; set; }
        public Nullable<System.Guid> idRefBookLandFrom { get; set; }
        public Nullable<System.Guid> idRefBookLandTo { get; set; }
        public Nullable<System.Guid> idRefBookETSNG { get; set; }
        public Nullable<System.Guid> idRefBookGNG { get; set; }
        public string DeliveryType { get; set; }
        public Nullable<System.Guid> RefBookStationFrom { get; set; }
        public Nullable<System.Guid> RefBookStationTo { get; set; }
        public string DepartuePoint { get; set; }
        public string DestinationPoint { get; set; }
        public string PointAdress { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public Nullable<System.Guid> Shipper { get; set; }
        public Nullable<System.Guid> Consignee { get; set; }
        public Nullable<System.Guid> idRailwayDispatch { get; set; }
        public Nullable<System.Guid> idRefBookCars { get; set; }
        public Nullable<System.Guid> idRefBookOwner { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> CargoUnitAmmount { get; set; }
        public Nullable<System.Guid> idSpecialCondition { get; set; }
        public string Note { get; set; }
        public string CargoUnitNumber1 { get; set; }
    
        public virtual DateMonth DateMonth { get; set; }
        public virtual RailwayDispatch RailwayDispatch { get; set; }
        public virtual SpecialCondition SpecialCondition { get; set; }
        public virtual TranshipmentMethod TranshipmentMethod { get; set; }
        public virtual RefBookCars RefBookCars { get; set; }
        public virtual RefBookClient RefBookClient { get; set; }
        public virtual RefBookClient RefBookClient1 { get; set; }
        public virtual RefBookETSNG RefBookETSNG { get; set; }
        public virtual RefBookGNG RefBookGNG { get; set; }
        public virtual RefBookLand RefBookLand { get; set; }
        public virtual RefBookLand RefBookLand1 { get; set; }
        public virtual RefBookOwner RefBookOwner { get; set; }
        public virtual RefBookStations RefBookStations { get; set; }
        public virtual RefBookStations RefBookStations1 { get; set; }
    }
}
