//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportFormASP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BTLC : DbContext
    {
        public BTLC()
            : base("name=BTLC")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DateMonth> DateMonth { get; set; }
        public virtual DbSet<RailwayDispatch> RailwayDispatch { get; set; }
        public virtual DbSet<SpecialCondition> SpecialCondition { get; set; }
        public virtual DbSet<TranshipmentMethod> TranshipmentMethod { get; set; }
        public virtual DbSet<TransportationRequest> TransportationRequest { get; set; }
        public virtual DbSet<RefBookCars> RefBookCars { get; set; }
        public virtual DbSet<RefBookClient> RefBookClient { get; set; }
        public virtual DbSet<RefBookETSNG> RefBookETSNG { get; set; }
        public virtual DbSet<RefBookGNG> RefBookGNG { get; set; }
        public virtual DbSet<RefBookLand> RefBookLand { get; set; }
        public virtual DbSet<RefBookOwner> RefBookOwner { get; set; }
        public virtual DbSet<RefBookStations> RefBookStations { get; set; }
    }
}
